name: "Build RGFW Quake For Windows"

on:
  push:

jobs:
  build-win32:
    name: "Build for Windows 32-bit"
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make TARGET=windows -j4 && mv quake.exe quake32.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quake32.exe
        path: quake32.exe

  build-win64:
    name: "Build for Windows 64-bit"
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make TARGET=windows -j4 && mv quake.exe quake64.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quake64.exe
        path: quake64.exe

  
