name: "Build RGFW Quake"

on:
  push:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build-win32:
    name: "Build for Windows 32-bit"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install mingw-w64
    - name: Build
      run: make TARGET=windows GCC_PREFIX=i686-w64-mingw32- -j4 && mv quake.exe ../quake32.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quake32
        path: quake32.exe

  build-win64:
    name: "Build for Windows 64-bit"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install mingw-w64
    - name: Build
      run: make TARGET=windows GCC_PREFIX=x86_64-w64-mingw32- -j4 && mv quake.exe ../quake64.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quake64
        path: quake64.exe

  release:
    name: "Release"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: [build-win32, build-win64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download from build-win32
      uses: actions/download-artifact@v4
      with:
        name: quake32
    - name: Download from build-win64
      uses: actions/download-artifact@v4
      with:
        name: quake64
    - name: Delete old release
      run: gh release delete "latest" --cleanup-tag -y || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      run: gh release create -t "latest" "latest" quake32.exe quake64.exe -n "Latest"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
