name: "Build RGFW Quake For Linux"

on:
  push:

jobs:
  build-win32:
    name: "Build for Linux 32-bit"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install -y --no-install-recommends libx11-dev mesa-common-dev libglx-dev libxcursor-dev mesa-vulkan-drivers libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libglu1-mesa-dev 
    - name: Build
      run: make && mv quake quake32-linux
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quake32-linux
        path: quake32-linux

  build-win64:
    name: "Build for Linux 64-bit"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install -y --no-install-recommends libx11-dev mesa-common-dev libglx-dev libxcursor-dev mesa-vulkan-drivers libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libglu1-mesa-dev 
    - name: Build
      run: make && mv quake quake64-linux
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quake64-linux
        path: quake64-linux

  release:
    name: "Release"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: [build-win32, build-win64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download from build-win32
      uses: actions/download-artifact@v4
      with:
        name: quake32-linux
    - name: Download from build-win64
      uses: actions/download-artifact@v4
      with:
        name: quake64-linux
    - name: Delete old release
      run: gh release delete "latest" --cleanup-tag -y || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      run: gh release create -t "latest" "latest" quake32-linux quake64-linux -n "Latest"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
