name: "Build RGFW Quake For MacOS"

on:
  push:

jobs:
  build-win32:
    name: "Build for MacOS 32-bit"
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: echo starting 
    - name: Build
      run: make && mv quake quake32-macos
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quake32-macos
        path: quake32-macos

  build-win64:
    name: "Build for MacOS 64-bit"
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: echo starting 
    - name: Build
      run: make && mv quake quake64-macos
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quake64-macos
        path: quake64-macos

  release:
    name: "Release"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: [build-win32, build-win64]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download from build-win32
      uses: actions/download-artifact@v4
      with:
        name: quake32-macos
    - name: Download from build-win64
      uses: actions/download-artifact@v4
      with:
        name: quake64-macos
    - name: Delete old release
      run: gh release delete "latest" --cleanup-tag -y || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      run: gh release create -t "latest" "latest" quake32-macos quake64-macos -n "Latest"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
